services:
  frontend:
    container_name: markdown-app-frontend
    build: ./frontend
    volumes:
      - ./frontend:/frontend-markdownapp
    ports:
      - "${APP_PORT}:8000"
    env_file: ["./frontend/.env"]
    depends_on:
      backend:
        condition: service_started
      redis:
        condition: service_healthy
    develop:
      watch:
        - action: sync+restart
          path: ./frontend
          target: /frontend-markdownapp
        - action: rebuild
          path: requirements.txt

  backend:
    container_name: "markdown-app-backend"
    build: ./backend
    volumes:
      - ./backend:/backend-markdownapp
    ports:
      - "${API_PORT}:8001"
    env_file: [ "./backend/.env" ]
    depends_on:
      mongodb:
        condition: service_healthy
    develop:
      watch:
        - action: sync+restart
          path: ./backend
          target: /backend-markdownapp
        - action: rebuild
          path: requirements.txt


  redis:
    image: redis:alpine
    container_name: markdown-app-redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    volumes:
      [redis-data:/data]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  mongodb:
    image: mongodb/mongodb-community-server:latest
    ports:
      - "27017:27017"
    hostname: mongodb
    restart: 'unless-stopped'
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
#      - MONGO_URL=mongodb://mongodb:${MONGODB_PORT}/markdown_app
      - MONGO_INITDB_DATABASE=${MONGODB_DB}
    container_name: markdown-app-mongodb
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    develop:
      watch:
        - action: rebuild
          path: ./mongo-init.js
          target: /docker-entrypoint-initdb.d/mongo-init.js
    healthcheck:
#      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      test: [ "CMD","mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 120s
      retries: 5
      start_period: 40s


volumes:
    redis-data:
        driver: local
#    mongodb:
#      external:
    mongo-data:
    mongo-config:


