services:
  frontend:
    container_name: markdown-app-frontend
    build: ./frontend
    volumes:
      - ./frontend:/frontend-markdownapp
    ports:
      - "${APP_PORT}:8000"
    environment:
#        could have put this in the env frontend file, but just for my own clarity sake
#       note: the naming of the key is essential, else wont work. both here or in env file
      - AWS_ACCESS_KEY_ID=${ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${SECRET_KEY}
      - AWS_DEFAULT_REGION=${S3_MARKDOWNAPP_REGION}
    env_file: ["./frontend/.env"]
    depends_on:
      backend:
        condition: service_healthy
      redis:
        condition: service_healthy
    develop:
      watch:
        - action: sync+restart
          path: ./frontend
          target: /frontend-markdownapp
        - action: rebuild
          path: requirements.txt

  backend:
    container_name: "markdown-app-backend"
    build: ./backend
    volumes:
      - ./backend:/backend-markdownapp
    ports:
      - "${API_PORT}:8001"
    env_file: [ "./backend/.env" ]
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://markdown-app-backend:8001/user/create_new?q=tobi@gmail.com" ]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 20s
    depends_on:
      mongodb:
        condition: service_healthy
    develop:
      watch:
        - action: sync+restart
          path: ./backend
          target: /backend-markdownapp
        - action: rebuild
          path: requirements.txt


  redis:
    image: redis:alpine
    container_name: markdown-app-redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    volumes:
      [redis-data:/data]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  mongodb:
    image: mongodb/mongodb-community-server:latest
    ports:
      - "27017:27017"
    hostname: mongodb
    restart: 'unless-stopped'
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_DB}
      - CUSTOM_USERNAME=${MONGODB_CUSTOM_USERNAME}
      - CUSTOM_PASSWORD=${MONGODB_PASSWORD}
    container_name: markdown-app-mongodb
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    develop:
      watch:
        - action: rebuild
          path: ./mongo-init.js
          target: /docker-entrypoint-initdb.d/mongo-init.js
    healthcheck:
      test: [ "CMD","mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 120s
      retries: 5
      start_period: 40s


volumes:
    redis-data:
        driver: local
#    mongodb:
#      external:
    mongo-data:
    mongo-config:


